baseURL = "https://sx.ix5.org/info/"
languageCode = "en-us"
title = "Sony Xperia Corner"
theme = "kube"
Paginate = 20

staticDir2 = "content/files"

[permalinks]
posts = "/post/:title/"
docs = "/:title/"

[Params]
  author = "ix5"
  # email = "myemail@myaddress.xxx"
  description = "Information about Sony Xperia devices and AOSP"
  subdescription = "Not in any way affiliated with Sony"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/"

[[menu.main]]
    name = "Posts"
    weight = -100
    url = "/posts/"

[[menu.main]]
    name = "Disclaimer"
    weight = -100
    url = "/disclaimer/"
