baseURL = "https://sx.ix5.org/info/"
languageCode = "en-us"
title = "Sony Xperia Corner"
theme = "kube"
description = "Information about Sony Xperia devices and AOSP"
Paginate = 4

[permalinks]
post = "/posts/:title/"
docs = "/docs/:title/"

[Params]
  author = "ix5"
  # email = "myemail@myaddress.xxx"

#[[menu.main]]
#    name = "Posts"
#    weight = -100
#    url = "/posts/"
